apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: my-second-app
  name: my-second-pod
spec:
  containers:
  - image: nginx
    name: nginx-container
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
