apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-deployment
    labels:
        app: nginx
        type: frontend
spec:
    replicas: 6
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
            name: nginx-pod
            labels:
                app: nginx
                type: frontend
        spec:
            containers:
                - name: nginx-container
                  image: nginx
