apiVersion: v1
data:
  PASSWORD: QUJDRA==
kind: Secret
metadata:
  creationTimestamp: "2020-11-17T17:37:02Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:PASSWORD: {}
      f:type: {}
    manager: kubectl-create
    operation: Update
    time: "2020-11-17T17:37:02Z"
  name: highly-secret
  namespace: default
  resourceVersion: "310619"
  selfLink: /api/v1/namespaces/default/secrets/highly-secret
  uid: fecc977b-9458-44dc-9966-7f6f9566b1e8
type: Opaque
